kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2                                                    
storageConfig:                                                      
  registry:
    imageURL: quay-enterpise.example.com/my_organization/operators-metadata:latest                 
    skipTLS: false
mirror:
  helm: